### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by JustinBeckwith** [google/google-p12-pem#13]
Would be great to publish 1.0 out to npm so we can start using it in our other modules!

**Comment by ofrobots** [comment]
PTAL at the draft release notes: https://github.com/google/google-p12-pem/releases/tag/untagged-66d764c3d8b5425c26ea

**Comment by JustinBeckwith** [comment]
I get a 404 for that link :/

**Comment by ofrobots** [comment]
Maybe here: https://github.com/google/google-p12-pem/releases

**Comment by ofrobots** [comment]
Perhaps only the author can view draft release notes?

**Comment by JustinBeckwith** [comment]
I can see that.  LGTM!

**Comment by ofrobots** [comment]
This was done.
