### ISSUE TITLE
Missing certificate on .pem output

### ISSUE THREAD

**Issue by knownasilya** [google/google-p12-pem#4]
I can get a valid pem using `openssl pkcs12 -in path.p12 -out newfile.pem -nodes`, which takes a password and returns a pem that contains the private key and the cert.

Probably due to only converting the private key to the pem.
https://github.com/ryanseys/google-p12-pem/blob/master/index.js#L54

**Comment by ofrobots** [comment]
I am cleaning up old issues on this repo. If this is still an issue, please re-open.
